---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  annotations: {{ .Values.service.annotations | toJson }}
  labels:
    app: {{ $.Release.Name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
spec:
  type: {{ .Values.service.type }}
  externalTrafficPolicy: Local
  ports:
    - port: 22
      targetPort: ssh
      protocol: TCP
{{- with .Values.service.nodePort }}
      nodePort: {{ . }}
{{- end }}
      name: ssh
  selector:
    app.kubernetes.io/instance: {{ .Release.Name }}
